### ISSUE TITLE
Update creates a new document with same ID instead of replacing old one.

### ISSUE THREAD

**Issue by joroGER** [bajankristof/nedb-promises#15]
```
> const Datastore = require("nedb-promises");
> db = new Datastore({ filename: path });
> db.load()
> db.insert({name: "Klaus", age: 12, msgs: []})
> db.insert({name: "Tina", age: 13, msgs: []})
{"name":"Klaus","age":12,"msgs":[],"_id":"tsLAT46b58ioadgd"}
{"name":"Tina","age":13,"msgs":[],"_id":"KFqE0KPY5Z1zY6To"}
> db.update({name: "Klaus"}, {$set:{name: "Bert"}}, {}).then(console.log("true")).catch(err => console.log(err));
true
{"name":"Klaus","age":12,"msgs":[],"_id":"tsLAT46b58ioadgd"}
{"name":"Tina","age":13,"msgs":[],"_id":"KFqE0KPY5Z1zY6To"}
{"name":"Bert","age":12,"msgs":[],"_id":"tsLAT46b58ioadgd"}
```

Am I missing something obvious here?
I found this solution https://github.com/louischatriot/nedb/issues/530 but this method does not seem to exist in nedb-promises

```
> db.persistence.compactDatafile()
TypeError: Cannot read property 'compactDatafile' of undefined
```

**Comment by bajankristof** [comment]
Hi,

First-off you should use `Datastore.create(...)` to create a datastore instance instead of `new Datastore(...)`, check out the docs:
https://github.com/bajankristof/nedb-promises/blob/master/docs.md#Datastore.create
This way you should be able to call `compactDatafile()`

Also about this part:
```json
{"name":"Klaus","age":12,"msgs":[],"_id":"tsLAT46b58ioadgd"}
{"name":"Tina","age":13,"msgs":[],"_id":"KFqE0KPY5Z1zY6To"}
{"name":"Bert","age":12,"msgs":[],"_id":"tsLAT46b58ioadgd"}
```
I'm guessing this from the datastore file itself and not a result of `datastore.find(...)`. 
If that's true: the way nedb works is that it inserts a new row for every update (or deletion) to the datastore file. That doesn't mean that the document is duplicated it's just the way nedb handles updates. Try running `datastore.find().then(console.log)` after the update and you should see that there are only 2 documents in your datastore. 

I hope this was helpful!
Feel free to close the issue if I managed to solve your problems :)

**Comment by joroGER** [comment]
Found the solution:
`db = new Datastore({ filename: databasePath });` works but not as expected
If I use `db = Datastore.create(databasePath);` instead I can call `db.persistence.compactDatafile()` and the old entry gets deleted as expected
