### ISSUE TITLE
high severity vulnerability

### ISSUE THREAD

**Issue by ironoa** [bajankristof/nedb-promises#45]
Hello,

`nedb` dependency ( https://github.com/bajankristof/nedb-promises/blob/master/package.json#L26 ) has an high severity vulnerability due to a dependency on `underscore`

![image](https://user-images.githubusercontent.com/25957738/118110772-1d923000-b3e3-11eb-81e9-3d2b877c37ff.png)

Since `nedb` is a dead project, a possible solution could be to rely on this forked and fixed version of the dependency: https://github.com/louischatriot/nedb/issues/675#issuecomment-837998714 => https://www.npmjs.com/package/@yetzt/nedb

**Comment by jimmywarting** [comment]
Should stop depending on nedb and fork it entirely and modernize everything!

**Comment by bajankristof** [comment]
Hi,

@ironoa thanks for opening this issue! I resolved the security vulnerability by overwriting the underscore versions in the dependencies. The problem is that the original `nedb` is still the most popular version of itself and I would rather not depend on something that is not verified by the community. Since you are using `3.x` of `nedb-promises`, I also published `3.0.8` with the fixed dependencies, so `4.1.4` and `3.0.8` should be free of this security vulnerability.

@jimmywarting that's not very constructive to be honest but I see where you're coming from on the idea. I do agree that sometimes it's better to just start over (that's my biggest problem with NodeJS, that this happens way to often). Unfortunately I just don't have the time to do that and since there hasn't been enough traction around a fork of `nedb`, I am not switching from the original code in this library either.

Anyway the issue should be solved with `4.1.4` and `3.0.8`. Please do check that the issue is resolved on your end and close the issue if it is.

Thanks

**Comment by bajankristof** [comment]
Oops, I may have broken something in the package, I'm on it

**Comment by tex0l** [comment]
@bajankristof would you be open to a PR that:
- embeds nedb within nedb-promises laong with the tests;
- rewrites nedb in modern JS completely;
- updates dependencies;

?

**Comment by bajankristof** [comment]
@tex0l interesting idea, but I feel like that would require even more time to maintain the project afterwards which I am barely capable of right now with this small wrapper

**Comment by tex0l** [comment]
As it is, nedb is unmaintained but fairly stable. I feel like something even a bit maintained is better than something totally unmaintained.

Since I upvoted @jimmywarting's comment 2 hours ago, I started working on this.
I currently have something that:
- embeds nedb and binary-search-tree and their tests (except benchmarks);
- has updated dependencies;
- doesn't use `var` anymore.

All tests pass, and works as a drop-in replacement for `nedb-promises`.

**Comment by tex0l** [comment]
You can take a look here: https://github.com/tex0l/nedb-promises/commits/master

**Comment by ByteDrummer** [comment]
Since this issue started, I switched over to linvodb3 which is a fork of nedb but uses leveldb as the backend. A promise wrapper for it would be nice as an alternative to embedding nedb. Just an idea though. Obviously it would be more work but at least linvodb3 is pretty active.

**Comment by jimmywarting** [comment]
> @bajankristof but I feel like that would require even more time to maintain the project

sounds like you could need a extra hand., Give @tex0l write access and make him to a maintainer - he seems devoted to keep it up🙂

**Comment by tex0l** [comment]
As explained in the draft PR #46, we decided to maintain a fork of nedb that is not vulnerable anymore: https://github.com/seald/nedb

**Comment by bajankristof** [comment]
Hi everyone, I know it's been a while, anyway `nedb-promises` `5.0.0` was just released to [npm](https://www.npmjs.com/package/nedb-promises) replacing `nedb` with `@seald-io/nedb` to resolve the vulnerability issue. It's a major version bump, because even though there hasn't been a breaking feature in `nedb-promises`, this change could be breaking for some users. For now I'm closing this issue but feel free to report back if anything's wrong.
