### ISSUE TITLE
Insert Multi if not-exists

### ISSUE THREAD

**Issue by ArchI3Chris** [bajankristof/nedb-promises#54]
Right now I'm testing nedb for a new project that I intend to start. So, I'm a beginner with nedb. But testing, i ran into some problem while just trying to populate my db with some dummy data. I took some time to try to find a solution, but didn't come across any useful so far. So, maybe someone more experience can help me out here.

I'm wondering... is there some option to tell nedb to actually insert non-existent entries instead of dropping everything upon multi-insert in case even just a single one exists?

Imagine the following scenario:

Let's say, I have 500 entries to insert. One of them already exists... in the database (not as double in the 500 entries!). Since entries have to be unique, for this ONE entry ALL 500 ARE BEING DROPPED in a multi-insert and nothing happens at all!

So, here is the problem with this particular scenario: neither checking for each entry one by one, nor running an update, which requires a query statement, make sense. Running them one by one requires like 500 queries + 500 inserts. Meaning 1000 separate interactions for 499 inserts or querying ALL data and checking it inside the app. Besides according code in the app itself. On top of it, if I have to check it one by one within the app anyway, what's the unique option for anyway? On the other hand, since there are 500 unique entries in the list, there is no reasonable query for an update. In fact, I could insert 5000 and 20 of them overlap. So, this sets me back to checking each one by one. Again... this makes the whole unique option fairly useless. If I have to check each entry one by one anyway, the whole unique option is absolutely useless.

Maybe it's just me. But I don't see the point of dropping 499 solid inserts for ONE that creates an issue.

So, is there any option to tell nedb to just insert the non-existing entries and just drop the one that is already in there, other than running through them one by one?

Btw... nedb seems interesting. But if anyone can offer a similar option that INCLUDES relational data (and maybe a solution to this one)... I'd appreciate suggestions.

**Comment by bajankristof** [comment]
Hi,

What you are experiencing here is on purpose. This kind of behaviour is called atomicity for databases. If an operation is atomic it guarantees the success or failure of the operation as a whole, meaning that if (like in your example) just one part of the operation fails the whole operation fails with it and everything remains the same on the storage level. This can be painful in some situations but amazing in others.

Just as an example when this is useful:
You store images and compression tasks in a datastore, the compression task is picked up by the app and the app compresses the image that is assigned to it to a desired size or format. When a user adds a new image you need to insert both an image and a compression task into the database. Now if it weren't for atomicity something could go wrong and you could end up with an image that is never going to be compressed because the compression task couldn't be inserted or you could end up with a compression task with an image assigned that doesn't exist because the image couldn't be inserted. With atomicity you (your app) is guaranteed to only succeed with the insert if both of the documents are successfully inserted. (I hope this explanation makes sense.)

As to what can be done here:
What I can think of off the top of my head is upserts in combination with `returnUpdatedDocs`. With that you could reduce the number of operations to `N` (`N` being the number of documents that you are trying to insert).
See the docs [here](https://github.com/bajankristof/nedb-promises/blob/master/docs.md#datastoreupdatequery-update-options--promisenumberobjectarrayobject).

I hope I was able to help you, have a nice day!

**Comment by ArchI3Chris** [comment]
Thanks. I appreciate the try to help. But to be honest, I don't see the purpose, nor does this help.

Personally, I use databases for storing data, not for compressing images. And as I explained in my question, the number of N operations on the side of the app, along with the according number of DB queries and requests is already a waste!

So, nedb doesn't actually reduce the number of queries here, it doesn't allow relational data and on top of it stores data in clear text files, which takes issues (like security or preventing direct user access) to a whole new level. Is this a student's project that came out of boredom? No offense. Just the impression I'm tempted to get here.

I'm tempted to say, it's just an alternative naming convention for functionality that already exists. Maybe it's no coincidence at all, that the basic nedb project has been dropped? Because it's basically file handling. At this point I'm tempted to assume, that I could just as well put the data into a file with JSON.stringify and am up to par with nedb? The difference is, I don't have to learn about nedb and it's function names and options, but can use default language functionality that everybody should know anyway and learn with the basics.

In fact, if you take a look at all the pages for nedb-promises and nedb, you'll find nothing that contradicts that statement. People just call it a "database" and MongoDB-like API. But let's face it. It's functions for file handling and if you pull it out of the file and put it into a variable in the app, you have it IN MEMORY. Btw... I'm wondering... did anyone think of the implications? Because in case the battery of your phone dies, your in-memory "database" is gone! If you turn off you PC, the in-memory "database" is gone. If you have a power loss at home... you get the picture, don't you? Also, do I really need a database for that? Or could I just use JSON in a variable for that? Seriously? So, what's the point?

So, what exactly is the advantage of nedb? Stuff like using $set, which I don't even need with MongoDB? While file handling should be among the basics to learn for a developer, this is just one more thing to learn, or is it not?

But of course that's just me. Again... I fail to see the purpose and I see many flaws in creating the need to go through data one by one. I doubt that most people would use a database to compress images instead of storing data. This doesn't help me one bit. I doubt, that most developers would consider it useful to worry about 500 operations instead of one. The purpose of added functionality should be, to actually make the live of a developer easier. Not to make it easy for the developer of the functionality and just drop the request of the person using it.

But maybe that's just me.

On the other hand... I wish people would do some more research and learn before they just repeat words they heard and use something they don't actually understand to explain something else. Did you actually research atomicity, what it is and how it should be used?

Let me pull this one from Google, which takes like 2 seconds to find upon research (meaning, I literally just copied your statement "atomicity for databases" and handed it to Google):

"_Atomicity means that multiple operations can be grouped into a single logical entity, that is, other threads of control accessing the database will either see all of the changes or none of the changes._"

So for some odd reason it seems, that the whole idea is to actually group multiple operations into one, while PREVENTING issues with parallel access, instead of rendering operations moot and creating issues with them. So, the same reasoning you use for the explanation, is actually the downfall of the statement. Based on that I'm tempted to assume, that it is maybe not just me at all and someone or some people misunderstood a thing or two. Maybe this stuff is actually meant to be used to the advantage of developers, instead of being in their way and killing their efforts?

Doesn't require a reply. Just food for thought. Thanks anyway. I sincerely appreciate your trying to help and maybe it actually helps you grow and improve too? Best wishes.



> Hi,
> 
> What you are experiencing here is on purpose. This kind of behaviour is called atomicity for databases. If an operation is atomic it guarantees the success or failure of the operation as a whole, meaning that if (like in your example) just one part of the operation fails the whole operation fails with it and everything remains the same on the storage level. This can be painful in some situations but amazing in others.
> 
> Just as an example when this is useful: You store images and compression tasks in a datastore, the compression task is picked up by the app and the app compresses the image that is assigned to it to a desired size or format. When a user adds a new image you need to insert both an image and a compression task into the database. Now if it weren't for atomicity something could go wrong and you could end up with an image that is never going to be compressed because the compression task couldn't be inserted or you could end up with a compression task with an image assigned that doesn't exist because the image couldn't be inserted. With atomicity you (your app) is guaranteed to only succeed with the insert if both of the documents are successfully inserted. (I hope this explanation makes sense.)
> 
> As to what can be done here: What I can think of off the top of my head is upserts in combination with `returnUpdatedDocs`. With that you could reduce the number of operations to `N` (`N` being the number of documents that you are trying to insert). See the docs [here](https://github.com/bajankristof/nedb-promises/blob/master/docs.md#datastoreupdatequery-update-options--promisenumberobjectarrayobject).
> 
> I hope I was able to help you, have a nice day!

**Comment by bajankristof** [comment]
First off, I'll let the honestly quite arrogant tone slide and try to shed some light on some stuff:

1. I did not create `nedb` so I don't know the reasoning behind the development, it could be out of boredom. I'm just the humble maintainer of a promise wrapper for the library.
2. Of course `nedb` is not meant to be used as database for web development projects, there are much better solutions for that. You can use `nedb` as a backup to store data in case the actual database is not available, or when working with electron for example where you might need to store (obviously non-sensitive) data on the clients computer.
3. `nedb` does persist data on the disk so I don't see the whole reasoning behind your in-memory rant.
4. Atomicity means exactly what I said it means in the example: "_database will either see all of the changes or none of the changes_".
5. As to what advantages `nedb` offers compared to plain JSON files is quite simple. It uses binary search trees to optimize queries to the database so you don't need to, it implements indexes so you don't need to. Otherwise you would be just going over an array of objects over and over again to retrieve the data you need.
6. As for growing myself, I'm constantly trying to improve. Are you? Maybe you should start with the tone you interact with people.
