### ISSUE TITLE
Datastore.create(path) doesn't create a file in the directory where it's called but in the process.env.pwd directory.

### ISSUE THREAD

**Issue by CryptoSharon** [bajankristof/nedb-promises#9]
I spent a few hours trying to use this module but no matter how I rewrote it, I didn't manage to have `Datastore.create(path)` create a file at path. The documents were inserted but they were held in memory. In the end, I went for `new Datastore` and it solved the issue at once. however, I wouldn't be able to use persistence if this were the only way.

The solution I thought up is not optimal. I would use `fs` to know if the file has been created already. If it has, I can safely use Datastore.create, but if not, I will need to use new Datastore, restart the app, then Datastore.create in order to use persistence.

**Comment by CryptoSharon** [comment]
Nevermind. I tried again to reproduce it after deleting a .db file in another folder and it worked. I think something is off but I can't quite place it. I'll close the issue, but if it resurfaces I'll post again.

**Comment by CryptoSharon** [comment]
Got it. The program creates the .db file in the parent folder. My folder structure is

```
.
├── db
├──── index.js
├── tools
├──── saver.js
├── src
└────  index.js
```

The program starts in `src`, `src` loads `tools`, `tools` loads `db` then inserts documents.

When `db` is loaded, the Datastore is created at "./default.db" in a document that is inside the folder `db`. However, the program interprets the "." as the home project instead of the folder where the db is stored. I have to call `Datastore.create('./db/default.db`)` in order for the database to be in the correct folder.

My code in `db/index.js` is:

```js
const Datastore = require('nedb-promises')

const db = Datastore.create({
  filename: './default.db',
  autoload: true
})

module.exports = db
```

It only works when filename includes the directory as if the call were being made in the home directory.

**Comment by bajankristof** [comment]
Hey, I'm looking at it just now. I'm not sure but I do feel like that's the intended way of operation. I'll check it out.

**Comment by bajankristof** [comment]
Yeah so as I suspected that is the intended way of operation and that's how the original module works (check out the attached zip, you can run `npm start` and `npm run start-original` to see for yourself). If you would like, I could add that to the documentation for clarification.
I'll wait for your confirmation on the issue. Cheers

[nedb-promises-issue9.zip](https://github.com/bajankristof/nedb-promises/files/2490272/nedb-promises-issue9.zip)

**Comment by CryptoSharon** [comment]
Confirmed D: I didn't know it worked like this.

I didn't use classical nedb much because I can't deal with not having promises. I came straight here from there. You could add it to the docs, I suppose. Is anyone else going to have this problem? I seem to have been the only one. And why is it like this? It seems like the only use for it would be the ability to call the database universally from any file. But would we want to do that? If we initialise the same file twice, write conflicts might occur.

**Comment by bajankristof** [comment]
I think that by design nedb looks up paths relative to the `process.cwd` not sure why, as a workaround you could always do:
```js
Datastore.create(`${__dirname}/default.db`)
```
I'll add this to the docs, until then I'll leave this issue opened.

**Comment by bajankristof** [comment]
#12

**Comment by acjay** [comment]
I seem to be having a similar issue. My database was creating just fine, but for reasons I can't figure, it doesn't seem to be doing so anymore. I've tried `Datastore.create('./db.db')` and also, since I'm using Electron, `Datastore.create(path.join(remote.app.getPath("userData"), "db.db"))`. I'm not seeing any files created, though. What's weird is that there was a `db.db` in my App Data folder before. It just stopped being created and accessed. Everything seems to be working in-memory, but I'm not seeing any errors. This is really frustrating.

**Comment by bajankristof** [comment]
@acjay The tests seem to be running fine. Did you check what `remote.app.getPath('userData')` returns in this case? I've seen electron remote threads behave weird so I wouldn't be surprised if that was the cause.

**Comment by acjay** [comment]
Yeah, I'm logging it out, and it returns the expected path. I am noticing that trying to write a document using regular `nedb` doesn't seem to be working either now.  Both work fine from Node REPL, but fail silently from my Electron renderer process in development. So I suppose it's probably not this package's fault. Have you ever heard of silent failure to actually write to a file? Thanks for the quick response.

**Comment by bajankristof** [comment]
No, I haven't heard of such case up until now. I'll try to replicate this and look into what's happening. So you're creating a simple renderer process and in that process you're calling `Datastore.create` right?

**Comment by acjay** [comment]
Hmm, I think it has something to do the whole `browser-version` subdirectory in nedb. I haven't puzzled out exactly how, but that code is being picked up by webpack instead of the node code. I'll have to figure out how to override this.

**Comment by acjay** [comment]
Yeah, so here it is: https://github.com/louischatriot/nedb/blob/master/package.json#L41-L44

Even though I'm using `"target": "electron-renderer"` in my Webpack config, it's still including those browser-specific variants in my bundle, which is why it's not writing to disk. I deleted just those lines in my local `package.json` and it fixed the issue. But that's not really a sustainable solution, so I'll have to figure out how to override that.

Thanks for responding. It's not really your problem at all, but I suspect if more people find that `nedb` is a good fit for Electron persistence and use Webpack to bundle their code and want a modern promise-based API, they might come across this.
